# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/shopStore.csproj
    - name: Build
      run: dotnet build ./src/shopStore.csproj --no-restore
    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'shopstore'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: #>
          #--failOnCVSS 7
          --enableRetired
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
          name: Depcheck report
          path: reports
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test ./test/shopStoreUnitTest/shopStoreUnitTest.csproj

  api-test:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Pull Postgres
        run: docker run -itd -e POSTGRES_USER=server_admin -e POSTGRES_PASSWORD=P@ssw0rd -p 5432:5432  --name postgresql postgres
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/iliass-de/shopstore:latest
          docker run -d -p 8080:80 ghcr.io/iliass-de/shopstore:latest
      - name: Prepare newman
        run: npm install -g newman
      - name: Run test with newman
        run: newman run ./test/api_test/api_tests.postman_collection.json --delay-request 1000

  publish:
    runs-on: ubuntu-latest
    needs: [build, test, api-test]
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/iliass-de/shopstore:latest
          docker run -d -p 8080:80 ghcr.io/iliass-de/shopstore:latest
          docker push ghcr.io/iliass-de/shopstore:latest
